app:
  name: "飞书任务Bot"
  version: "0.1.0"

feishu:
  app_id: ${FEISHU_APP_ID}
  app_secret: ${FEISHU_APP_SECRET}
  encrypt_key: ${FEISHU_ENCRYPT_KEY}
  verification_token: ${FEISHU_VERIFICATION_TOKEN}

server:
  host: ${HOST}
  port: 8000
  public_url: ${PUBLIC_URL}

llm:
  default_provider: "deepseek"
  providers:
    deepseek:
      model: "deepseek-chat"
      api_key: ${DEEPSEEK_KEY}
    gemini:
      model: "gemini-pro"
      api_key: ${GEMINI_KEY}
    openai:
      model: "gpt-4-turbo"
      api_key: ${OPENAI_KEY}

task:
  acceptance_threshold: 80
  max_revisions: 2
  reminder_hours: 48
  
github:
  webhook_secret: ${GITHUB_WEBHOOK_SECRET: ""}

bitable:
  app_token: ${BITABLE_APP_TOKEN}
  task_table_id: ${BITABLE_TASK_TABLE_ID}
  person_table_id: ${BITABLE_PERSON_TABLE_ID} 